language: node_js

node_js:
  - "lts/*"

addons:
  chrome: stable

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache

jobs:
  include:
    - stage: Test
      env:
        - NODE_ENV=testing
      name: Frontend Tests
      install: cd client && npm ci
      script: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI
    - script:
      - npm run build:prod
      - npm run cy:verify
      - npm run ci:cy-run
      install: cd client && npm ci
      before_script:
        - cd ..
        - npm start & wait-on http://localhost:3000 &
      name: E2E tests
    - script: npm run test
      name: Backend tests
