language: node_js

node_js:
  - "lts/*"

addons:
  chrome: stable

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ./node_modules
    - ~/.cache

jobs:
  include:
    - stage: Test
      env:
        - NODE_ENV=testing
      name: Frontend Tests
      install: cd client && npm ci
      script: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI
    - script:
      - cd ..
      - npm ci
      - npm run build
      - npm run start:test &
      - cd client
      - npm run cy:verify
      - npm run ci:cy-run
      install: cd client && npm ci
      name: E2E tests
    - script: npm run test
      name: Backend tests
      
    - stage: deploy
      if: branch = master
      deploy:
        provider: netlify
        site: https://pokern.netlify.app
        edge: true # opt in to dpl v2
        dir: "client/dist/"

